### ISSUE TITLE
About superpoint graph constructed

### ISSUE THREAD

**Issue by RayYoh** [zju3dv/SAM-Graph#3]
Dear authors,

Thanks for your great work, and I look forward to the released code.
Now, my question is, are there any methods (specifically the code) provided for ScanNet++ to get their superpoints. To the best knowledge, ScanNetV2 provided the segmentor in their official repo.

Looking forward to your reply.

Best

**Comment by ghy0324** [comment]
Hi! Thanks for your interest! When we conduct experiments on the ScanNet++ dataset, we also use [the segmentator from ScanNet repository](https://github.com/ScanNet/ScanNet/tree/master/Segmentator).
